feat(yadm): improve bootstrap script with logs and user prompts

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,24 +1,35 @@
-#!/bin/bash
-
-# Save this file as ~/.config/yadm/bootstrap and make it executable. It will
-# execute all executable files (excluding templates and editor backups) in the
-# ~/.config/yadm/bootstrap.d directory when run.
-
-set -eu
+#!/bin/env sh
+source ~/.config/yadm/bootstrap.tools
 
 # Directory to look for bootstrap executables in
 BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
 
 if [[ ! -d "$BOOTSTRAP_D" ]]; then
-    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
+    error "bootstrap directory '${BOOTSTRAP_D}' not found"
     exit 1
 fi
 
-find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
-    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
-        if ! "$bootstrap"; then
-            echo "Error: bootstrap '$bootstrap' failed" >&2
-            exit 1
+# Check if running as root, and prompt for password if not
+if [ "$EUID" -ne 0 ]; then
+  warn "Elevated permissions are required to adjust system settings."
+  warn "Please enter your password..."
+  sudo -v
+
+  if [ $? -ne 0 ]; then
+    error "Unable to elevate permissions"
+    exit 1
+  fi
+fi
+
+find -L "${BOOTSTRAP_D}" -type f | sort | while IFS= read -r bootstrap; do
+    if [[ -x "${bootstrap}" && ! "${bootstrap}" =~ "##" && ! "${bootstrap}" =~ "~$" ]]; then
+        status "Running ${bootstrap}"
+        if ! . ${bootstrap}; then
+          fail "Running ${bootstrap}"
+          # error "bootstrap script '$bootstrap' failed"
+          # exit 1
+        else
+          success "Running ${bootstrap}"
         fi
     fi
 done
